import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <div className={styles.grid}>
          <Link href="ssr" className={styles.card}>
            <h2>Server Side Rendering (SSR) &rarr;</h2>
          </Link>
        </div>
        <div className={styles.grid}>
          <Link href="ssr/ssr-advice" className={styles.card}>
            <h2>Server Side Rendering (SSR) - Advice API &rarr;</h2>
          </Link>
        </div>

        <div className={styles.grid}>
          <Link href="ssg" className={styles.card}>
            <h2>Static Site Generation (SSG) &rarr;</h2>
          </Link>
        </div>
        <div className={styles.grid}>
          <Link href="ssg/ssg-advice" className={styles.card}>
            <h2>Static Site Generation (SSG) - Advice API &rarr;</h2>
          </Link>
        </div>

        <div className={styles.grid}>
          <Link href="csr" className={styles.card}>
            <h2>Client Side Rendering (CSR) &rarr;</h2>
          </Link>
        </div>
        <div className={styles.grid}>
          <Link href="csr/csr-suspense" className={styles.card}>
            <h2>Client Side Rendering (CSR) with Suspense&rarr;</h2>
          </Link>
        </div>

        <div className={styles.grid}>
          <Link href="isr" className={styles.card}>
            <h2>Incremental Static Regeneration (ISR) &rarr;</h2>
          </Link>
        </div>

        <div className={styles.grid}>
          <Link href="rsc" className={styles.card}>
            <h2>React Server Components - RSC (experimental!) &rarr;</h2>
          </Link>
        </div>

        <div className={styles.grid}>
          <Link href="ssr-react-query" className={styles.card}>
            <h2>You can also combine SSG/SSR and CSR! This one uses SSR + CSR (via react-query and GraphQL) &rarr;</h2>
          </Link>
        </div>

        <div className={styles.grid}>
          <Link href="rerender" className={styles.card}>
            <h2>Concurrent React &rarr;</h2>
          </Link>
        </div>

        <div className={styles.grid}>
          <Link href="non-existent-path" className={styles.card}>
            <h2>Where do non existent paths go? &rarr;</h2>
          </Link>
        </div>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
